import { LCUClient } from "./client";

export const SCORE_TEST_DATAS: LCUClient.IGameMatch = {
  accountId: 4111091085,
  games: {
    gameBeginDate: "",
    gameCount: 175,
    gameEndDate: "",
    gameIndexBegin: 0,
    gameIndexEnd: 10,
    games: [
      {
        gameCreation: 1650086949995,
        gameCreationDate: "2022-04-16T05:29:09.995Z",
        gameDuration: 1690,
        gameId: 6861432015,
        gameMode: "CLASSIC",
        gameType: "MATCHED_GAME",
        gameVersion: "12.7.433.4138",
        mapId: 11,
        participantIdentities: [
          {
            participantId: 0,
            player: {
              accountId: 4111091085,
              currentAccountId: 4111091085,
              currentPlatformId: "HN1",
              matchHistoryUri: "/v1/stats/player_history/HN1/4111091085",
              platformId: "HN1",
              profileIcon: 4849,
              summonerId: 4111091085,
              summonerName: "小枫需要冷静",
            },
          },
        ],
        participants: [
          {
            championId: 81,
            highestAchievedSeasonTier: "",
            participantId: 0,
            spell1Id: 7,
            spell2Id: 4,
            stats: {
              assists: 10,
              causedEarlySurrender: false,
              champLevel: 14,
              combatPlayerScore: 0,
              damageDealtToObjectives: 10964,
              damageDealtToTurrets: 4638,
              damageSelfMitigated: 7286,
              deaths: 5,
              doubleKills: 0,
              earlySurrenderAccomplice: false,
              firstBloodAssist: false,
              firstBloodKill: false,
              firstInhibitorAssist: false,
              firstInhibitorKill: false,
              firstTowerAssist: false,
              firstTowerKill: false,
              gameEndedInEarlySurrender: false,
              gameEndedInSurrender: false,
              goldEarned: 10610,
              goldSpent: 10050,
              inhibitorKills: 0,
              item0: 1055,
              item1: 3042,
              item2: 3508,
              item3: 3158,
              item4: 6655,
              item5: 0,
              item6: 3340,
              killingSprees: 0,
              kills: 4,
              largestCriticalStrike: 437,
              largestKillingSpree: 0,
              largestMultiKill: 1,
              longestTimeSpentLiving: 653,
              magicDamageDealt: 14990,
              magicDamageDealtToChampions: 7325,
              magicalDamageTaken: 8899,
              neutralMinionsKilled: 13,
              neutralMinionsKilledEnemyJungle: 4,
              neutralMinionsKilledTeamJungle: 5,
              objectivePlayerScore: 0,
              participantId: 0,
              pentaKills: 0,
              perk0: 8005,
              perk0Var1: 305,
              perk0Var2: 233,
              perk0Var3: 71,
              perk1: 8009,
              perk1Var1: 1465,
              perk1Var2: 0,
              perk1Var3: 0,
              perk2: 9103,
              perk2Var1: 23,
              perk2Var2: 10,
              perk2Var3: 0,
              perk3: 8014,
              perk3Var1: 367,
              perk3Var2: 0,
              perk3Var3: 0,
              perk4: 8304,
              perk4Var1: 9,
              perk4Var2: 4,
              perk4Var3: 5,
              perk5: 8345,
              perk5Var1: 3,
              perk5Var2: 0,
              perk5Var3: 0,
              perkPrimaryStyle: 8000,
              perkSubStyle: 8300,
              physicalDamageDealt: 102257,
              physicalDamageDealtToChampions: 10979,
              physicalDamageTaken: 7258,
              playerScore0: 0,
              playerScore1: 0,
              playerScore2: 0,
              playerScore3: 0,
              playerScore4: 0,
              playerScore5: 0,
              playerScore6: 0,
              playerScore7: 0,
              playerScore8: 0,
              playerScore9: 0,
              quadraKills: 0,
              sightWardsBoughtInGame: 0,
              teamEarlySurrendered: false,
              timeCCingOthers: 0,
              totalDamageDealt: 120496,
              totalDamageDealtToChampions: 18304,
              totalDamageTaken: 17116,
              totalHeal: 3609,
              totalMinionsKilled: 157,
              totalPlayerScore: 0,
              totalScoreRank: 0,
              totalTimeCrowdControlDealt: 1,
              totalUnitsHealed: 4,
              tripleKills: 0,
              trueDamageDealt: 3247,
              trueDamageDealtToChampions: 0,
              trueDamageTaken: 958,
              turretKills: 1,
              unrealKills: 0,
              visionScore: 15,
              visionWardsBoughtInGame: 0,
              wardsKilled: 1,
              wardsPlaced: 8,
              win: true,
            },
            teamId: 200,
            timeline: {
              creepsPerMinDeltas: { "0-10": 6.3, "10-20": 6.5 },
              csDiffPerMinDeltas: {
                "0-10": 0.1499999999999997,
                "10-20": -0.24999999999999975,
              },
              damageTakenDiffPerMinDeltas: {
                "0-10": 48.14999999999998,
                "10-20": -36.900000000000034,
              },
              damageTakenPerMinDeltas: { "0-10": 266.6, "10-20": 537.9 },
              goldPerMinDeltas: { "0-10": 287.1, "10-20": 391.3 },
              lane: "BOTTOM",
              participantId: 0,
              role: "DUO_CARRY",
              xpDiffPerMinDeltas: {
                "0-10": -20.900000000000038,
                "10-20": -91.79999999999995,
              },
              xpPerMinDeltas: { "0-10": 317.4, "10-20": 388.6 },
            },
          },
        ],
        platformId: "HN1",
        queueId: 440,
        seasonId: 0,
        teams: [],
      },
      {
        gameCreation: 1650088920167,
        gameCreationDate: "2022-04-16T06:02:00.167Z",
        gameDuration: 2006,
        gameId: 6861483731,
        gameMode: "CLASSIC",
        gameType: "MATCHED_GAME",
        gameVersion: "12.7.433.4138",
        mapId: 11,
        participantIdentities: [
          {
            participantId: 0,
            player: {
              accountId: 4111091085,
              currentAccountId: 4111091085,
              currentPlatformId: "HN1",
              matchHistoryUri: "/v1/stats/player_history/HN1/4111091085",
              platformId: "HN1",
              profileIcon: 4849,
              summonerId: 4111091085,
              summonerName: "小枫需要冷静",
            },
          },
        ],
        participants: [
          {
            championId: 21,
            highestAchievedSeasonTier: "",
            participantId: 0,
            spell1Id: 7,
            spell2Id: 4,
            stats: {
              assists: 17,
              causedEarlySurrender: false,
              champLevel: 17,
              combatPlayerScore: 0,
              damageDealtToObjectives: 24165,
              damageDealtToTurrets: 6598,
              damageSelfMitigated: 5720,
              deaths: 5,
              doubleKills: 2,
              earlySurrenderAccomplice: false,
              firstBloodAssist: false,
              firstBloodKill: false,
              firstInhibitorAssist: false,
              firstInhibitorKill: false,
              firstTowerAssist: false,
              firstTowerKill: true,
              gameEndedInEarlySurrender: false,
              gameEndedInSurrender: true,
              goldEarned: 15987,
              goldSpent: 14200,
              inhibitorKills: 0,
              item0: 3031,
              item1: 6672,
              item2: 3006,
              item3: 6676,
              item4: 3033,
              item5: 1018,
              item6: 3340,
              killingSprees: 2,
              kills: 9,
              largestCriticalStrike: 897,
              largestKillingSpree: 3,
              largestMultiKill: 2,
              longestTimeSpentLiving: 841,
              magicDamageDealt: 3242,
              magicDamageDealtToChampions: 1244,
              magicalDamageTaken: 10501,
              neutralMinionsKilled: 55,
              neutralMinionsKilledEnemyJungle: 4,
              neutralMinionsKilledTeamJungle: 45,
              objectivePlayerScore: 0,
              participantId: 0,
              pentaKills: 0,
              perk0: 8229,
              perk0Var1: 1321,
              perk0Var2: 0,
              perk0Var3: 0,
              perk1: 8226,
              perk1Var1: 250,
              perk1Var2: 903,
              perk1Var3: 0,
              perk2: 8233,
              perk2Var1: 21,
              perk2Var2: 30,
              perk2Var3: 0,
              perk3: 8237,
              perk3Var1: 410,
              perk3Var2: 0,
              perk3Var3: 0,
              perk4: 8304,
              perk4Var1: 10,
              perk4Var2: 3,
              perk4Var3: 0,
              perk5: 8345,
              perk5Var1: 3,
              perk5Var2: 0,
              perk5Var3: 0,
              perkPrimaryStyle: 8200,
              perkSubStyle: 8300,
              physicalDamageDealt: 185028,
              physicalDamageDealtToChampions: 23789,
              physicalDamageTaken: 9135,
              playerScore0: 0,
              playerScore1: 0,
              playerScore2: 0,
              playerScore3: 0,
              playerScore4: 0,
              playerScore5: 0,
              playerScore6: 0,
              playerScore7: 0,
              playerScore8: 0,
              playerScore9: 0,
              quadraKills: 0,
              sightWardsBoughtInGame: 0,
              teamEarlySurrendered: false,
              timeCCingOthers: 8,
              totalDamageDealt: 210771,
              totalDamageDealtToChampions: 26991,
              totalDamageTaken: 20769,
              totalHeal: 1804,
              totalMinionsKilled: 188,
              totalPlayerScore: 0,
              totalScoreRank: 0,
              totalTimeCrowdControlDealt: 148,
              totalUnitsHealed: 5,
              tripleKills: 0,
              trueDamageDealt: 22500,
              trueDamageDealtToChampions: 1957,
              trueDamageTaken: 1132,
              turretKills: 2,
              unrealKills: 0,
              visionScore: 23,
              visionWardsBoughtInGame: 0,
              wardsKilled: 4,
              wardsPlaced: 11,
              win: true,
            },
            teamId: 100,
            timeline: {
              creepsPerMinDeltas: { "0-10": 7.5, "10-20": 6.3, "20-30": 3.8 },
              csDiffPerMinDeltas: {},
              damageTakenDiffPerMinDeltas: {},
              damageTakenPerMinDeltas: {
                "0-10": 134.10000000000002,
                "10-20": 571.9000000000001,
                "20-30": 1027.1,
              },
              goldPerMinDeltas: {
                "0-10": 302.4,
                "10-20": 381.4,
                "20-30": 627.9000000000001,
              },
              lane: "MIDDLE",
              participantId: 0,
              role: "DUO",
              xpDiffPerMinDeltas: {},
              xpPerMinDeltas: { "0-10": 285, "10-20": 386.3, "20-30": 763.2 },
            },
          },
        ],
        platformId: "HN1",
        queueId: 440,
        seasonId: 0,
        teams: [],
      },
      {
        gameCreation: 1650091245821,
        gameCreationDate: "2022-04-16T06:40:45.821Z",
        gameDuration: 2053,
        gameId: 6861557258,
        gameMode: "CLASSIC",
        gameType: "MATCHED_GAME",
        gameVersion: "12.7.433.4138",
        mapId: 11,
        participantIdentities: [
          {
            participantId: 0,
            player: {
              accountId: 4111091085,
              currentAccountId: 4111091085,
              currentPlatformId: "HN1",
              matchHistoryUri: "/v1/stats/player_history/HN1/4111091085",
              platformId: "HN1",
              profileIcon: 4849,
              summonerId: 4111091085,
              summonerName: "小枫需要冷静",
            },
          },
        ],
        participants: [
          {
            championId: 15,
            highestAchievedSeasonTier: "",
            participantId: 0,
            spell1Id: 7,
            spell2Id: 4,
            stats: {
              assists: 11,
              causedEarlySurrender: false,
              champLevel: 15,
              combatPlayerScore: 0,
              damageDealtToObjectives: 5282,
              damageDealtToTurrets: 5282,
              damageSelfMitigated: 6596,
              deaths: 7,
              doubleKills: 0,
              earlySurrenderAccomplice: false,
              firstBloodAssist: false,
              firstBloodKill: true,
              firstInhibitorAssist: false,
              firstInhibitorKill: false,
              firstTowerAssist: false,
              firstTowerKill: false,
              gameEndedInEarlySurrender: false,
              gameEndedInSurrender: false,
              goldEarned: 12452,
              goldSpent: 11950,
              inhibitorKills: 0,
              item0: 3042,
              item1: 7002,
              item2: 3158,
              item3: 6694,
              item4: 3134,
              item5: 1018,
              item6: 3363,
              killingSprees: 1,
              kills: 4,
              largestCriticalStrike: 0,
              largestKillingSpree: 2,
              largestMultiKill: 1,
              longestTimeSpentLiving: 574,
              magicDamageDealt: 257,
              magicDamageDealtToChampions: 141,
              magicalDamageTaken: 5521,
              neutralMinionsKilled: 22,
              neutralMinionsKilledEnemyJungle: 4,
              neutralMinionsKilledTeamJungle: 18,
              objectivePlayerScore: 0,
              participantId: 0,
              pentaKills: 0,
              perk0: 8128,
              perk0Var1: 816,
              perk0Var2: 13,
              perk0Var3: 0,
              perk1: 8139,
              perk1Var1: 1654,
              perk1Var2: 0,
              perk1Var3: 0,
              perk2: 8138,
              perk2Var1: 18,
              perk2Var2: 0,
              perk2Var3: 0,
              perk3: 8135,
              perk3Var1: 400,
              perk3Var2: 5,
              perk3Var3: 0,
              perk4: 8210,
              perk4Var1: 7,
              perk4Var2: 0,
              perk4Var3: 0,
              perk5: 8226,
              perk5Var1: 250,
              perk5Var2: 2040,
              perk5Var3: 0,
              perkPrimaryStyle: 8100,
              perkSubStyle: 8200,
              physicalDamageDealt: 189467,
              physicalDamageDealtToChampions: 21767,
              physicalDamageTaken: 12491,
              playerScore0: 0,
              playerScore1: 0,
              playerScore2: 0,
              playerScore3: 0,
              playerScore4: 0,
              playerScore5: 0,
              playerScore6: 0,
              playerScore7: 0,
              playerScore8: 0,
              playerScore9: 0,
              quadraKills: 0,
              sightWardsBoughtInGame: 0,
              teamEarlySurrendered: false,
              timeCCingOthers: 3,
              totalDamageDealt: 190617,
              totalDamageDealtToChampions: 22669,
              totalDamageTaken: 18013,
              totalHeal: 3808,
              totalMinionsKilled: 196,
              totalPlayerScore: 0,
              totalScoreRank: 0,
              totalTimeCrowdControlDealt: 104,
              totalUnitsHealed: 4,
              tripleKills: 0,
              trueDamageDealt: 892,
              trueDamageDealtToChampions: 760,
              trueDamageTaken: 0,
              turretKills: 2,
              unrealKills: 0,
              visionScore: 15,
              visionWardsBoughtInGame: 0,
              wardsKilled: 1,
              wardsPlaced: 11,
              win: false,
            },
            teamId: 200,
            timeline: {
              creepsPerMinDeltas: { "0-10": 5.3, "10-20": 6.7, "20-30": 4.5 },
              csDiffPerMinDeltas: {},
              damageTakenDiffPerMinDeltas: {},
              damageTakenPerMinDeltas: {
                "0-10": 287.20000000000005,
                "10-20": 397.4,
                "20-30": 751.6,
              },
              goldPerMinDeltas: {
                "0-10": 304.20000000000005,
                "10-20": 368.8,
                "20-30": 338,
              },
              lane: "JUNGLE",
              participantId: 0,
              role: "NONE",
              xpDiffPerMinDeltas: {},
              xpPerMinDeltas: { "0-10": 265.9, "10-20": 382, "20-30": 389.2 },
            },
          },
        ],
        platformId: "HN1",
        queueId: 440,
        seasonId: 0,
        teams: [],
      },
      {
        gameCreation: 1650093634776,
        gameCreationDate: "2022-04-16T07:20:34.776Z",
        gameDuration: 2103,
        gameId: 6861692159,
        gameMode: "CLASSIC",
        gameType: "MATCHED_GAME",
        gameVersion: "12.7.433.4138",
        mapId: 11,
        participantIdentities: [
          {
            participantId: 0,
            player: {
              accountId: 4111091085,
              currentAccountId: 4111091085,
              currentPlatformId: "HN1",
              matchHistoryUri: "/v1/stats/player_history/HN1/4111091085",
              platformId: "HN1",
              profileIcon: 4849,
              summonerId: 4111091085,
              summonerName: "小枫需要冷静",
            },
          },
        ],
        participants: [
          {
            championId: 21,
            highestAchievedSeasonTier: "",
            participantId: 0,
            spell1Id: 7,
            spell2Id: 4,
            stats: {
              assists: 5,
              causedEarlySurrender: false,
              champLevel: 17,
              combatPlayerScore: 0,
              damageDealtToObjectives: 42165,
              damageDealtToTurrets: 9469,
              damageSelfMitigated: 8997,
              deaths: 7,
              doubleKills: 2,
              earlySurrenderAccomplice: false,
              firstBloodAssist: false,
              firstBloodKill: false,
              firstInhibitorAssist: false,
              firstInhibitorKill: false,
              firstTowerAssist: false,
              firstTowerKill: false,
              gameEndedInEarlySurrender: false,
              gameEndedInSurrender: false,
              goldEarned: 20234,
              goldSpent: 20900,
              inhibitorKills: 2,
              item0: 3033,
              item1: 6672,
              item2: 3006,
              item3: 6676,
              item4: 3031,
              item5: 3072,
              item6: 3340,
              killingSprees: 4,
              kills: 18,
              largestCriticalStrike: 1141,
              largestKillingSpree: 8,
              largestMultiKill: 4,
              longestTimeSpentLiving: 711,
              magicDamageDealt: 8792,
              magicDamageDealtToChampions: 3765,
              magicalDamageTaken: 6279,
              neutralMinionsKilled: 60,
              neutralMinionsKilledEnemyJungle: 8,
              neutralMinionsKilledTeamJungle: 33,
              objectivePlayerScore: 0,
              participantId: 0,
              pentaKills: 0,
              perk0: 8229,
              perk0Var1: 2180,
              perk0Var2: 0,
              perk0Var3: 0,
              perk1: 8226,
              perk1Var1: 250,
              perk1Var2: 1131,
              perk1Var3: 0,
              perk2: 8233,
              perk2Var1: 17,
              perk2Var2: 50,
              perk2Var3: 0,
              perk3: 8237,
              perk3Var1: 695,
              perk3Var2: 0,
              perk3Var3: 0,
              perk4: 8304,
              perk4Var1: 11,
              perk4Var2: 1,
              perk4Var3: 5,
              perk5: 8345,
              perk5Var1: 3,
              perk5Var2: 0,
              perk5Var3: 0,
              perkPrimaryStyle: 8200,
              perkSubStyle: 8300,
              physicalDamageDealt: 218294,
              physicalDamageDealtToChampions: 31477,
              physicalDamageTaken: 12546,
              playerScore0: 0,
              playerScore1: 0,
              playerScore2: 0,
              playerScore3: 0,
              playerScore4: 0,
              playerScore5: 0,
              playerScore6: 0,
              playerScore7: 0,
              playerScore8: 0,
              playerScore9: 0,
              quadraKills: 1,
              sightWardsBoughtInGame: 0,
              teamEarlySurrendered: false,
              timeCCingOthers: 12,
              totalDamageDealt: 249565,
              totalDamageDealtToChampions: 39960,
              totalDamageTaken: 22948,
              totalHeal: 3879,
              totalMinionsKilled: 198,
              totalPlayerScore: 0,
              totalScoreRank: 0,
              totalTimeCrowdControlDealt: 221,
              totalUnitsHealed: 2,
              tripleKills: 2,
              trueDamageDealt: 22479,
              trueDamageDealtToChampions: 4717,
              trueDamageTaken: 4122,
              turretKills: 3,
              unrealKills: 0,
              visionScore: 23,
              visionWardsBoughtInGame: 0,
              wardsKilled: 2,
              wardsPlaced: 11,
              win: true,
            },
            teamId: 100,
            timeline: {
              creepsPerMinDeltas: {
                "0-10": 7.1,
                "10-20": 7.1,
                "20-30": 4.4,
                "30-end": 2.4,
              },
              csDiffPerMinDeltas: {
                "0-10": 0.09999999999999964,
                "10-20": 0.4999999999999998,
                "20-30": -0.5999999999999999,
                "30-end": 0.5999999999999999,
              },
              damageTakenDiffPerMinDeltas: {
                "0-10": -8.799999999999983,
                "10-20": -43.85000000000002,
                "20-30": 134.74999999999994,
                "30-end": 218.5999999999999,
              },
              damageTakenPerMinDeltas: {
                "0-10": 154.3,
                "10-20": 343.29999999999995,
                "20-30": 1156.5,
                "30-end": 1281.4,
              },
              goldPerMinDeltas: {
                "0-10": 250.2,
                "10-20": 651.4,
                "20-30": 616.8,
                "30-end": 908.6,
              },
              lane: "BOTTOM",
              participantId: 0,
              role: "DUO_CARRY",
              xpDiffPerMinDeltas: {
                "0-10": -58.40000000000002,
                "10-20": 111.25,
                "20-30": -239.40000000000003,
                "30-end": 213.80000000000007,
              },
              xpPerMinDeltas: {
                "0-10": 248.8,
                "10-20": 503.1,
                "20-30": 595.3,
                "30-end": 713.8,
              },
            },
          },
        ],
        platformId: "HN1",
        queueId: 440,
        seasonId: 0,
        teams: [],
      },
      {
        gameCreation: 1650201391469,
        gameCreationDate: "2022-04-17T13:16:31.469Z",
        gameDuration: 1037,
        gameId: 6865795646,
        gameMode: "CLASSIC",
        gameType: "MATCHED_GAME",
        gameVersion: "12.7.433.4138",
        mapId: 11,
        participantIdentities: [
          {
            participantId: 0,
            player: {
              accountId: 4111091085,
              currentAccountId: 4111091085,
              currentPlatformId: "HN1",
              matchHistoryUri: "/v1/stats/player_history/HN1/4111091085",
              platformId: "HN1",
              profileIcon: 4849,
              summonerId: 4111091085,
              summonerName: "小枫需要冷静",
            },
          },
        ],
        participants: [
          {
            championId: 21,
            highestAchievedSeasonTier: "",
            participantId: 0,
            spell1Id: 7,
            spell2Id: 4,
            stats: {
              assists: 2,
              causedEarlySurrender: false,
              champLevel: 9,
              combatPlayerScore: 0,
              damageDealtToObjectives: 10240,
              damageDealtToTurrets: 10240,
              damageSelfMitigated: 1672,
              deaths: 0,
              doubleKills: 0,
              earlySurrenderAccomplice: false,
              firstBloodAssist: false,
              firstBloodKill: false,
              firstInhibitorAssist: true,
              firstInhibitorKill: false,
              firstTowerAssist: true,
              firstTowerKill: false,
              gameEndedInEarlySurrender: false,
              gameEndedInSurrender: false,
              goldEarned: 7523,
              goldSpent: 6200,
              inhibitorKills: 1,
              item0: 1055,
              item1: 6672,
              item2: 3009,
              item3: 3134,
              item4: 1018,
              item5: 0,
              item6: 3340,
              killingSprees: 1,
              kills: 3,
              largestCriticalStrike: 504,
              largestKillingSpree: 3,
              largestMultiKill: 1,
              longestTimeSpentLiving: 0,
              magicDamageDealt: 1129,
              magicDamageDealtToChampions: 649,
              magicalDamageTaken: 2144,
              neutralMinionsKilled: 4,
              neutralMinionsKilledEnemyJungle: 4,
              neutralMinionsKilledTeamJungle: 0,
              objectivePlayerScore: 0,
              participantId: 0,
              pentaKills: 0,
              perk0: 8229,
              perk0Var1: 760,
              perk0Var2: 0,
              perk0Var3: 0,
              perk1: 8226,
              perk1Var1: 250,
              perk1Var2: 270,
              perk1Var3: 0,
              perk2: 8233,
              perk2Var1: 8,
              perk2Var2: 0,
              perk2Var3: 0,
              perk3: 8237,
              perk3Var1: 284,
              perk3Var2: 0,
              perk3Var3: 0,
              perk4: 8304,
              perk4Var1: 11,
              perk4Var2: 1,
              perk4Var3: 5,
              perk5: 8345,
              perk5Var1: 3,
              perk5Var2: 0,
              perk5Var3: 0,
              perkPrimaryStyle: 8200,
              perkSubStyle: 8300,
              physicalDamageDealt: 67618,
              physicalDamageDealtToChampions: 5203,
              physicalDamageTaken: 2351,
              playerScore0: 0,
              playerScore1: 0,
              playerScore2: 0,
              playerScore3: 0,
              playerScore4: 0,
              playerScore5: 0,
              playerScore6: 0,
              playerScore7: 0,
              playerScore8: 0,
              playerScore9: 0,
              quadraKills: 0,
              sightWardsBoughtInGame: 0,
              teamEarlySurrendered: false,
              timeCCingOthers: 3,
              totalDamageDealt: 73073,
              totalDamageDealtToChampions: 6051,
              totalDamageTaken: 4496,
              totalHeal: 597,
              totalMinionsKilled: 131,
              totalPlayerScore: 0,
              totalScoreRank: 0,
              totalTimeCrowdControlDealt: 34,
              totalUnitsHealed: 2,
              tripleKills: 0,
              trueDamageDealt: 4325,
              trueDamageDealtToChampions: 197,
              trueDamageTaken: 0,
              turretKills: 2,
              unrealKills: 0,
              visionScore: 7,
              visionWardsBoughtInGame: 0,
              wardsKilled: 1,
              wardsPlaced: 4,
              win: true,
            },
            teamId: 200,
            timeline: {
              creepsPerMinDeltas: { "0-10": 8 },
              csDiffPerMinDeltas: { "0-10": 1.9799999999999995 },
              damageTakenDiffPerMinDeltas: { "0-10": 130.26000000000002 },
              damageTakenPerMinDeltas: { "0-10": 141.1 },
              goldPerMinDeltas: { "0-10": 309.3 },
              lane: "NONE",
              participantId: 0,
              role: "DUO",
              xpDiffPerMinDeltas: { "0-10": 173.8 },
              xpPerMinDeltas: { "0-10": 298.29999999999995 },
            },
          },
        ],
        platformId: "HN1",
        queueId: 440,
        seasonId: 0,
        teams: [],
      },
      {
        gameCreation: 1650202903176,
        gameCreationDate: "2022-04-17T13:41:43.176Z",
        gameDuration: 1620,
        gameId: 6866019249,
        gameMode: "CLASSIC",
        gameType: "MATCHED_GAME",
        gameVersion: "12.7.433.4138",
        mapId: 11,
        participantIdentities: [
          {
            participantId: 0,
            player: {
              accountId: 4111091085,
              currentAccountId: 4111091085,
              currentPlatformId: "HN1",
              matchHistoryUri: "/v1/stats/player_history/HN1/4111091085",
              platformId: "HN1",
              profileIcon: 4849,
              summonerId: 4111091085,
              summonerName: "小枫需要冷静",
            },
          },
        ],
        participants: [
          {
            championId: 81,
            highestAchievedSeasonTier: "",
            participantId: 0,
            spell1Id: 7,
            spell2Id: 4,
            stats: {
              assists: 11,
              causedEarlySurrender: false,
              champLevel: 14,
              combatPlayerScore: 0,
              damageDealtToObjectives: 14640,
              damageDealtToTurrets: 7698,
              damageSelfMitigated: 6511,
              deaths: 4,
              doubleKills: 1,
              earlySurrenderAccomplice: false,
              firstBloodAssist: false,
              firstBloodKill: false,
              firstInhibitorAssist: true,
              firstInhibitorKill: false,
              firstTowerAssist: false,
              firstTowerKill: false,
              gameEndedInEarlySurrender: false,
              gameEndedInSurrender: false,
              goldEarned: 12057,
              goldSpent: 11050,
              inhibitorKills: 0,
              item0: 1055,
              item1: 3158,
              item2: 3508,
              item3: 3042,
              item4: 6691,
              item5: 3133,
              item6: 3363,
              killingSprees: 1,
              kills: 6,
              largestCriticalStrike: 581,
              largestKillingSpree: 6,
              largestMultiKill: 2,
              longestTimeSpentLiving: 645,
              magicDamageDealt: 14259,
              magicDamageDealtToChampions: 4939,
              magicalDamageTaken: 3785,
              neutralMinionsKilled: 14,
              neutralMinionsKilledEnemyJungle: 8,
              neutralMinionsKilledTeamJungle: 6,
              objectivePlayerScore: 0,
              participantId: 0,
              pentaKills: 0,
              perk0: 8005,
              perk0Var1: 408,
              perk0Var2: 317,
              perk0Var3: 90,
              perk1: 8009,
              perk1Var1: 2890,
              perk1Var2: 0,
              perk1Var3: 0,
              perk2: 9103,
              perk2Var1: 20,
              perk2Var2: 10,
              perk2Var3: 0,
              perk3: 8014,
              perk3Var1: 422,
              perk3Var2: 0,
              perk3Var3: 0,
              perk4: 8304,
              perk4Var1: 9,
              perk4Var2: 4,
              perk4Var3: 5,
              perk5: 8345,
              perk5Var1: 3,
              perk5Var2: 0,
              perk5Var3: 0,
              perkPrimaryStyle: 8000,
              perkSubStyle: 8300,
              physicalDamageDealt: 105076,
              physicalDamageDealtToChampions: 16537,
              physicalDamageTaken: 10162,
              playerScore0: 0,
              playerScore1: 0,
              playerScore2: 0,
              playerScore3: 0,
              playerScore4: 0,
              playerScore5: 0,
              playerScore6: 0,
              playerScore7: 0,
              playerScore8: 0,
              playerScore9: 0,
              quadraKills: 0,
              sightWardsBoughtInGame: 0,
              teamEarlySurrendered: false,
              timeCCingOthers: 2,
              totalDamageDealt: 122242,
              totalDamageDealtToChampions: 21753,
              totalDamageTaken: 14265,
              totalHeal: 2326,
              totalMinionsKilled: 144,
              totalPlayerScore: 0,
              totalScoreRank: 0,
              totalTimeCrowdControlDealt: 26,
              totalUnitsHealed: 4,
              tripleKills: 0,
              trueDamageDealt: 2906,
              trueDamageDealtToChampions: 276,
              trueDamageTaken: 317,
              turretKills: 4,
              unrealKills: 0,
              visionScore: 6,
              visionWardsBoughtInGame: 0,
              wardsKilled: 0,
              wardsPlaced: 6,
              win: true,
            },
            teamId: 200,
            timeline: {
              creepsPerMinDeltas: { "0-10": 6.6, "10-20": 5.2 },
              csDiffPerMinDeltas: {
                "0-10": -1.2000000000000002,
                "10-20": -0.8499999999999999,
              },
              damageTakenDiffPerMinDeltas: {
                "0-10": 24.85000000000001,
                "10-20": 11.199999999999989,
              },
              damageTakenPerMinDeltas: {
                "0-10": 225.1,
                "10-20": 741.5999999999999,
              },
              goldPerMinDeltas: { "0-10": 253.6, "10-20": 386.7 },
              lane: "BOTTOM",
              participantId: 0,
              role: "DUO_CARRY",
              xpDiffPerMinDeltas: {
                "0-10": -32.44999999999999,
                "10-20": -26.39999999999995,
              },
              xpPerMinDeltas: { "0-10": 301.29999999999995, "10-20": 372.9 },
            },
          },
        ],
        platformId: "HN1",
        queueId: 440,
        seasonId: 0,
        teams: [],
      },
      {
        gameCreation: 1650204844768,
        gameCreationDate: "2022-04-17T14:14:04.768Z",
        gameDuration: 1225,
        gameId: 6866136484,
        gameMode: "CLASSIC",
        gameType: "MATCHED_GAME",
        gameVersion: "12.7.433.4138",
        mapId: 11,
        participantIdentities: [
          {
            participantId: 0,
            player: {
              accountId: 4111091085,
              currentAccountId: 4111091085,
              currentPlatformId: "HN1",
              matchHistoryUri: "/v1/stats/player_history/HN1/4111091085",
              platformId: "HN1",
              profileIcon: 4849,
              summonerId: 4111091085,
              summonerName: "小枫需要冷静",
            },
          },
        ],
        participants: [
          {
            championId: 21,
            highestAchievedSeasonTier: "",
            participantId: 0,
            spell1Id: 7,
            spell2Id: 4,
            stats: {
              assists: 6,
              causedEarlySurrender: false,
              champLevel: 9,
              combatPlayerScore: 0,
              damageDealtToObjectives: 3150,
              damageDealtToTurrets: 1616,
              damageSelfMitigated: 4250,
              deaths: 8,
              doubleKills: 1,
              earlySurrenderAccomplice: false,
              firstBloodAssist: false,
              firstBloodKill: false,
              firstInhibitorAssist: false,
              firstInhibitorKill: false,
              firstTowerAssist: false,
              firstTowerKill: false,
              gameEndedInEarlySurrender: false,
              gameEndedInSurrender: false,
              goldEarned: 6949,
              goldSpent: 6900,
              inhibitorKills: 0,
              item0: 6692,
              item1: 3004,
              item2: 0,
              item3: 3006,
              item4: 0,
              item5: 0,
              item6: 3363,
              killingSprees: 1,
              kills: 3,
              largestCriticalStrike: 481,
              largestKillingSpree: 2,
              largestMultiKill: 2,
              longestTimeSpentLiving: 416,
              magicDamageDealt: 3626,
              magicDamageDealtToChampions: 1060,
              magicalDamageTaken: 5471,
              neutralMinionsKilled: 12,
              neutralMinionsKilledEnemyJungle: 0,
              neutralMinionsKilledTeamJungle: 9,
              objectivePlayerScore: 0,
              participantId: 0,
              pentaKills: 0,
              perk0: 8229,
              perk0Var1: 815,
              perk0Var2: 0,
              perk0Var3: 0,
              perk1: 8226,
              perk1Var1: 250,
              perk1Var2: 337,
              perk1Var3: 0,
              perk2: 8233,
              perk2Var1: 13,
              perk2Var2: 20,
              perk2Var3: 0,
              perk3: 8237,
              perk3Var1: 311,
              perk3Var2: 0,
              perk3Var3: 0,
              perk4: 8304,
              perk4Var1: 9,
              perk4Var2: 0,
              perk4Var3: 0,
              perk5: 8345,
              perk5Var1: 3,
              perk5Var2: 0,
              perk5Var3: 0,
              perkPrimaryStyle: 8200,
              perkSubStyle: 8300,
              physicalDamageDealt: 44238,
              physicalDamageDealtToChampions: 7695,
              physicalDamageTaken: 5325,
              playerScore0: 0,
              playerScore1: 0,
              playerScore2: 0,
              playerScore3: 0,
              playerScore4: 0,
              playerScore5: 0,
              playerScore6: 0,
              playerScore7: 0,
              playerScore8: 0,
              playerScore9: 0,
              quadraKills: 0,
              sightWardsBoughtInGame: 0,
              teamEarlySurrendered: false,
              timeCCingOthers: 5,
              totalDamageDealt: 50470,
              totalDamageDealtToChampions: 8755,
              totalDamageTaken: 11508,
              totalHeal: 567,
              totalMinionsKilled: 88,
              totalPlayerScore: 0,
              totalScoreRank: 0,
              totalTimeCrowdControlDealt: 102,
              totalUnitsHealed: 3,
              tripleKills: 0,
              trueDamageDealt: 2605,
              trueDamageDealtToChampions: 0,
              trueDamageTaken: 712,
              turretKills: 0,
              unrealKills: 0,
              visionScore: 11,
              visionWardsBoughtInGame: 0,
              wardsKilled: 1,
              wardsPlaced: 6,
              win: false,
            },
            teamId: 200,
            timeline: {
              creepsPerMinDeltas: { "0-10": 5.1, "10-20": 3.7 },
              csDiffPerMinDeltas: {
                "0-10": -0.5,
                "10-20": -1.4499999999999995,
              },
              damageTakenDiffPerMinDeltas: {
                "0-10": -96.95,
                "10-20": 494.00000000000006,
              },
              damageTakenPerMinDeltas: {
                "0-10": 257.20000000000005,
                "10-20": 893.6,
              },
              goldPerMinDeltas: { "0-10": 281.8, "10-20": 357.9 },
              lane: "BOTTOM",
              participantId: 0,
              role: "DUO_CARRY",
              xpDiffPerMinDeltas: {
                "0-10": -27.39999999999999,
                "10-20": -219.85,
              },
              xpPerMinDeltas: { "0-10": 262.5, "10-20": 349.29999999999995 },
            },
          },
        ],
        platformId: "HN1",
        queueId: 440,
        seasonId: 0,
        teams: [],
      },
      {
        gameCreation: 1650697749413,
        gameCreationDate: "2022-04-23T07:09:09.413Z",
        gameDuration: 1125,
        gameId: 6880175215,
        gameMode: "CLASSIC",
        gameType: "MATCHED_GAME",
        gameVersion: "12.7.433.4138",
        mapId: 11,
        participantIdentities: [
          {
            participantId: 0,
            player: {
              accountId: 4111091085,
              currentAccountId: 4111091085,
              currentPlatformId: "HN1",
              matchHistoryUri: "/v1/stats/player_history/HN1/4111091085",
              platformId: "HN1",
              profileIcon: 4849,
              summonerId: 4111091085,
              summonerName: "小枫需要冷静",
            },
          },
        ],
        participants: [
          {
            championId: 81,
            highestAchievedSeasonTier: "",
            participantId: 0,
            spell1Id: 7,
            spell2Id: 4,
            stats: {
              assists: 1,
              causedEarlySurrender: false,
              champLevel: 10,
              combatPlayerScore: 0,
              damageDealtToObjectives: 13007,
              damageDealtToTurrets: 9354,
              damageSelfMitigated: 2295,
              deaths: 2,
              doubleKills: 0,
              earlySurrenderAccomplice: false,
              firstBloodAssist: false,
              firstBloodKill: false,
              firstInhibitorAssist: true,
              firstInhibitorKill: false,
              firstTowerAssist: false,
              firstTowerKill: false,
              gameEndedInEarlySurrender: false,
              gameEndedInSurrender: false,
              goldEarned: 7826,
              goldSpent: 6850,
              inhibitorKills: 0,
              item0: 3004,
              item1: 0,
              item2: 3508,
              item3: 3158,
              item4: 0,
              item5: 0,
              item6: 3340,
              killingSprees: 0,
              kills: 2,
              largestCriticalStrike: 370,
              largestKillingSpree: 0,
              largestMultiKill: 1,
              longestTimeSpentLiving: 545,
              magicDamageDealt: 9601,
              magicDamageDealtToChampions: 3468,
              magicalDamageTaken: 1541,
              neutralMinionsKilled: 8,
              neutralMinionsKilledEnemyJungle: 0,
              neutralMinionsKilledTeamJungle: 4,
              objectivePlayerScore: 0,
              participantId: 0,
              pentaKills: 0,
              perk0: 8369,
              perk0Var1: 388,
              perk0Var2: 354,
              perk0Var3: 0,
              perk1: 8304,
              perk1Var1: 10,
              perk1Var2: 3,
              perk1Var3: 0,
              perk2: 8345,
              perk2Var1: 3,
              perk2Var2: 0,
              perk2Var3: 0,
              perk3: 8347,
              perk3Var1: 0,
              perk3Var2: 0,
              perk3Var3: 0,
              perk4: 8017,
              perk4Var1: 303,
              perk4Var2: 0,
              perk4Var3: 0,
              perk5: 9103,
              perk5Var1: 0,
              perk5Var2: 0,
              perk5Var3: 0,
              perkPrimaryStyle: 8300,
              perkSubStyle: 8000,
              physicalDamageDealt: 69030,
              physicalDamageDealtToChampions: 6703,
              physicalDamageTaken: 4063,
              playerScore0: 0,
              playerScore1: 0,
              playerScore2: 0,
              playerScore3: 0,
              playerScore4: 0,
              playerScore5: 0,
              playerScore6: 0,
              playerScore7: 0,
              playerScore8: 0,
              playerScore9: 0,
              quadraKills: 0,
              sightWardsBoughtInGame: 0,
              teamEarlySurrendered: false,
              timeCCingOthers: 1,
              totalDamageDealt: 79916,
              totalDamageDealtToChampions: 10770,
              totalDamageTaken: 6865,
              totalHeal: 879,
              totalMinionsKilled: 132,
              totalPlayerScore: 0,
              totalScoreRank: 0,
              totalTimeCrowdControlDealt: 25,
              totalUnitsHealed: 3,
              tripleKills: 0,
              trueDamageDealt: 1284,
              trueDamageDealtToChampions: 598,
              trueDamageTaken: 1260,
              turretKills: 3,
              unrealKills: 0,
              visionScore: 4,
              visionWardsBoughtInGame: 0,
              wardsKilled: 0,
              wardsPlaced: 3,
              win: true,
            },
            teamId: 100,
            timeline: {
              creepsPerMinDeltas: { "0-10": 6.7 },
              csDiffPerMinDeltas: { "0-10": 1.46 },
              damageTakenDiffPerMinDeltas: { "0-10": 54.37999999999997 },
              damageTakenPerMinDeltas: { "0-10": 273.1 },
              goldPerMinDeltas: { "0-10": 308.4 },
              lane: "NONE",
              participantId: 0,
              role: "DUO_SUPPORT",
              xpDiffPerMinDeltas: { "0-10": 127.56 },
              xpPerMinDeltas: { "0-10": 290.79999999999995 },
            },
          },
        ],
        platformId: "HN1",
        queueId: 440,
        seasonId: 0,
        teams: [],
      },
      {
        gameCreation: 1650699232240,
        gameCreationDate: "2022-04-23T07:33:52.240Z",
        gameDuration: 1808,
        gameId: 6880255558,
        gameMode: "CLASSIC",
        gameType: "MATCHED_GAME",
        gameVersion: "12.7.433.4138",
        mapId: 11,
        participantIdentities: [
          {
            participantId: 0,
            player: {
              accountId: 4111091085,
              currentAccountId: 4111091085,
              currentPlatformId: "HN1",
              matchHistoryUri: "/v1/stats/player_history/HN1/4111091085",
              platformId: "HN1",
              profileIcon: 4849,
              summonerId: 4111091085,
              summonerName: "小枫需要冷静",
            },
          },
        ],
        participants: [
          {
            championId: 21,
            highestAchievedSeasonTier: "",
            participantId: 0,
            spell1Id: 7,
            spell2Id: 4,
            stats: {
              assists: 5,
              causedEarlySurrender: false,
              champLevel: 13,
              combatPlayerScore: 0,
              damageDealtToObjectives: 6829,
              damageDealtToTurrets: 2616,
              damageSelfMitigated: 9697,
              deaths: 10,
              doubleKills: 1,
              earlySurrenderAccomplice: false,
              firstBloodAssist: false,
              firstBloodKill: true,
              firstInhibitorAssist: false,
              firstInhibitorKill: false,
              firstTowerAssist: false,
              firstTowerKill: true,
              gameEndedInEarlySurrender: false,
              gameEndedInSurrender: true,
              goldEarned: 13113,
              goldSpent: 12675,
              inhibitorKills: 0,
              item0: 3033,
              item1: 6672,
              item2: 3006,
              item3: 6676,
              item4: 1038,
              item5: 1037,
              item6: 3340,
              killingSprees: 2,
              kills: 8,
              largestCriticalStrike: 691,
              largestKillingSpree: 3,
              largestMultiKill: 3,
              longestTimeSpentLiving: 489,
              magicDamageDealt: 5395,
              magicDamageDealtToChampions: 1907,
              magicalDamageTaken: 4824,
              neutralMinionsKilled: 24,
              neutralMinionsKilledEnemyJungle: 0,
              neutralMinionsKilledTeamJungle: 21,
              objectivePlayerScore: 0,
              participantId: 0,
              pentaKills: 0,
              perk0: 8128,
              perk0Var1: 1043,
              perk0Var2: 17,
              perk0Var3: 0,
              perk1: 8139,
              perk1Var1: 1101,
              perk1Var2: 0,
              perk1Var3: 0,
              perk2: 8138,
              perk2Var1: 18,
              perk2Var2: 0,
              perk2Var3: 0,
              perk3: 8106,
              perk3Var1: 4,
              perk3Var2: 0,
              perk3Var3: 0,
              perk4: 9103,
              perk4Var1: 19,
              perk4Var2: 30,
              perk4Var3: 0,
              perk5: 9111,
              perk5Var1: 500,
              perk5Var2: 260,
              perk5Var3: 0,
              perkPrimaryStyle: 8100,
              perkSubStyle: 8000,
              physicalDamageDealt: 147310,
              physicalDamageDealtToChampions: 20068,
              physicalDamageTaken: 14781,
              playerScore0: 0,
              playerScore1: 0,
              playerScore2: 0,
              playerScore3: 0,
              playerScore4: 0,
              playerScore5: 0,
              playerScore6: 0,
              playerScore7: 0,
              playerScore8: 0,
              playerScore9: 0,
              quadraKills: 0,
              sightWardsBoughtInGame: 0,
              teamEarlySurrendered: false,
              timeCCingOthers: 7,
              totalDamageDealt: 164825,
              totalDamageDealtToChampions: 24421,
              totalDamageTaken: 22023,
              totalHeal: 2867,
              totalMinionsKilled: 198,
              totalPlayerScore: 0,
              totalScoreRank: 0,
              totalTimeCrowdControlDealt: 100,
              totalUnitsHealed: 3,
              tripleKills: 1,
              trueDamageDealt: 12119,
              trueDamageDealtToChampions: 2445,
              trueDamageTaken: 2417,
              turretKills: 1,
              unrealKills: 0,
              visionScore: 15,
              visionWardsBoughtInGame: 0,
              wardsKilled: 1,
              wardsPlaced: 9,
              win: false,
            },
            teamId: 100,
            timeline: {
              creepsPerMinDeltas: { "0-10": 6.7, "10-20": 8.1, "20-30": 5 },
              csDiffPerMinDeltas: {},
              damageTakenDiffPerMinDeltas: {},
              damageTakenPerMinDeltas: {
                "0-10": 288,
                "10-20": 697.9000000000001,
                "20-30": 1216.4,
              },
              goldPerMinDeltas: {
                "0-10": 349.1,
                "10-20": 488.6,
                "20-30": 421.8,
              },
              lane: "MIDDLE",
              participantId: 0,
              role: "DUO",
              xpDiffPerMinDeltas: {},
              xpPerMinDeltas: {
                "0-10": 264.6,
                "10-20": 397.7000000000001,
                "20-30": 445.1,
              },
            },
          },
        ],
        platformId: "HN1",
        queueId: 440,
        seasonId: 0,
        teams: [],
      },
      {
        gameCreation: 1650701396753,
        gameCreationDate: "2022-04-23T08:09:56.753Z",
        gameDuration: 1587,
        gameId: 6880390759,
        gameMode: "CLASSIC",
        gameType: "MATCHED_GAME",
        gameVersion: "12.7.433.4138",
        mapId: 11,
        participantIdentities: [
          {
            participantId: 0,
            player: {
              accountId: 4111091085,
              currentAccountId: 4111091085,
              currentPlatformId: "HN1",
              matchHistoryUri: "/v1/stats/player_history/HN1/4111091085",
              platformId: "HN1",
              profileIcon: 4849,
              summonerId: 4111091085,
              summonerName: "小枫需要冷静",
            },
          },
        ],
        participants: [
          {
            championId: 222,
            highestAchievedSeasonTier: "",
            participantId: 0,
            spell1Id: 7,
            spell2Id: 4,
            stats: {
              assists: 7,
              causedEarlySurrender: false,
              champLevel: 12,
              combatPlayerScore: 0,
              damageDealtToObjectives: 1362,
              damageDealtToTurrets: 0,
              damageSelfMitigated: 5545,
              deaths: 10,
              doubleKills: 0,
              earlySurrenderAccomplice: false,
              firstBloodAssist: false,
              firstBloodKill: false,
              firstInhibitorAssist: false,
              firstInhibitorKill: false,
              firstTowerAssist: false,
              firstTowerKill: false,
              gameEndedInEarlySurrender: false,
              gameEndedInSurrender: true,
              goldEarned: 7980,
              goldSpent: 7800,
              inhibitorKills: 0,
              item0: 6672,
              item1: 3094,
              item2: 3006,
              item3: 1018,
              item4: 0,
              item5: 0,
              item6: 3340,
              killingSprees: 1,
              kills: 3,
              largestCriticalStrike: 309,
              largestKillingSpree: 2,
              largestMultiKill: 1,
              longestTimeSpentLiving: 368,
              magicDamageDealt: 2652,
              magicDamageDealtToChampions: 1029,
              magicalDamageTaken: 4201,
              neutralMinionsKilled: 8,
              neutralMinionsKilledEnemyJungle: 0,
              neutralMinionsKilledTeamJungle: 5,
              objectivePlayerScore: 0,
              participantId: 0,
              pentaKills: 0,
              perk0: 8008,
              perk0Var1: 15,
              perk0Var2: 2,
              perk0Var3: 0,
              perk1: 8009,
              perk1Var1: 1137,
              perk1Var2: 0,
              perk1Var3: 0,
              perk2: 9103,
              perk2Var1: 0,
              perk2Var2: 0,
              perk2Var3: 0,
              perk3: 8014,
              perk3Var1: 150,
              perk3Var2: 0,
              perk3Var3: 0,
              perk4: 8304,
              perk4Var1: 9,
              perk4Var2: 4,
              perk4Var3: 5,
              perk5: 8345,
              perk5Var1: 3,
              perk5Var2: 0,
              perk5Var3: 0,
              perkPrimaryStyle: 8000,
              perkSubStyle: 8300,
              physicalDamageDealt: 55726,
              physicalDamageDealtToChampions: 9470,
              physicalDamageTaken: 14186,
              playerScore0: 0,
              playerScore1: 0,
              playerScore2: 0,
              playerScore3: 0,
              playerScore4: 0,
              playerScore5: 0,
              playerScore6: 0,
              playerScore7: 0,
              playerScore8: 0,
              playerScore9: 0,
              quadraKills: 0,
              sightWardsBoughtInGame: 0,
              teamEarlySurrendered: false,
              timeCCingOthers: 10,
              totalDamageDealt: 61411,
              totalDamageDealtToChampions: 11239,
              totalDamageTaken: 19262,
              totalHeal: 2836,
              totalMinionsKilled: 90,
              totalPlayerScore: 0,
              totalScoreRank: 0,
              totalTimeCrowdControlDealt: 51,
              totalUnitsHealed: 4,
              tripleKills: 0,
              trueDamageDealt: 3032,
              trueDamageDealtToChampions: 740,
              trueDamageTaken: 874,
              turretKills: 0,
              unrealKills: 0,
              visionScore: 13,
              visionWardsBoughtInGame: 0,
              wardsKilled: 1,
              wardsPlaced: 8,
              win: false,
            },
            teamId: 200,
            timeline: {
              creepsPerMinDeltas: { "0-10": 3.7, "10-20": 3.4 },
              csDiffPerMinDeltas: {},
              damageTakenDiffPerMinDeltas: {},
              damageTakenPerMinDeltas: {
                "0-10": 395.2000000000001,
                "10-20": 660.7,
              },
              goldPerMinDeltas: { "0-10": 209.3, "10-20": 330.5 },
              lane: "BOTTOM",
              participantId: 0,
              role: "DUO_CARRY",
              xpDiffPerMinDeltas: {},
              xpPerMinDeltas: { "0-10": 235.9, "10-20": 383.7 },
            },
          },
        ],
        platformId: "HN1",
        queueId: 440,
        seasonId: 0,
        teams: [],
      },
    ],
  },
  platformId: "HN1",
};
